### ISSUE TITLE
/sys/class/ionopi/ not created

### ISSUE THREAD

**Issue by operez06** [sfera-labs/iono-pi-kernel-module#1]
Hi,

During the installation, once all files were downloaded from the repository like:

- git clone --depth 1 https://github.com/sfera-labs/iono-pi-kernel-module.git 

- cd iono-pi-kernel-module

- make

I received this error:

**make -C /lib/modules/5.4.51-v7l+/build/ M=/home/pi/iono-pi-kernel-module modules
make[1]: Entering directory '/usr/src/linux-headers-5.4.51-v7l+'
  CC [M]  /home/pi/iono-pi-kernel-module/module.o
/home/pi/iono-pi-kernel-module/module.c: In function ‘diff_usec’:
/home/pi/iono-pi-kernel-module/module.c:861:9: error: implicit declaration of function ‘timespec_sub’; did you mean ‘timespec64_sub’? [-Werror=implicit-function-declaration]
  diff = timespec_sub(*t2, *t1);
         ^~~~~~~~~~~~
         timespec64_sub
/home/pi/iono-pi-kernel-module/module.c:861:7: error: incompatible types when assigning to type ‘struct timespec’ from type ‘int’
  diff = timespec_sub(*t2, *t1);
       ^
cc1: some warnings being treated as errors
make[2]: *** [scripts/Makefile.build:266: /home/pi/iono-pi-kernel-module/module.o] Error 1
make[1]: *** [Makefile:1709: /home/pi/iono-pi-kernel-module] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-5.4.51-v7l+'
make: *** [Makefile:6: all] Error 2**

Any idea?

Thanks

**Comment by giampiero7** [comment]
Issue due to function removal/renaming in kernel version >= 5.0
Fixed in 0c46692ff630bcedef1214dfafe4fa757570ff69

**Comment by operez06** [comment]
Thank you, appreciate the quick response.

**Comment by aliciasotobono** [comment]
I have the same error @operez06  but I don't get the warnings. How can I add your edited code to the installation? @giampiero7

**Comment by giampiero7** [comment]
Hello @aliciasotobono ,
You can just download the latest version of this repo and repeat the installation steps.
If the issue persist, please write the details here.

**Comment by aliciasotobono** [comment]
Hi @giampiero7,

I tried it again. I don´t get any errors, only this warning when the dtc "Warning (unit_address_vs_reg)" but when I continue the process I don´t get any other warning or error. The only issue is later that the folder /sys/class/ionopi/ doesn´t exist and if I try to read or anything it says that folder doesn´t exist. What should I do? Thank you for your help.

**Comment by giampiero7** [comment]
Hello @aliciasotobono ,
Can you please copy here the whole sequence of commands and the output you get?
Moreover, plese add the output of these commands:
```
uname -a
cat /etc/os-release
cat /proc/cpuinfo
dmesg | grep iono
```
