### ISSUE TITLE
Analog input read

### ISSUE THREAD

**Issue by Dalidos** [sfera-labs/iono-pi-kernel-module#2]
Hello

I made a quick Python script to check the voltage values ​​in the analog inputs of the Iono pi. 
Analog input 1: AI1 -> 1000 mV go to the input
Analog input 2: AI2 -> 6000 mV go to the input

And here's what I see:

`AI1:  980 , AI2:  5877`
`AI1:  980 , AI2:  5877`
`AI1:  973 , AI2:  5877`
`AI1:  973 , AI2:  5884`
`AI1:  5877 , AI2:  5884`  <--
`AI1:  980 , AI2:  5877`
`AI1:  973 , AI2:  5884`
`AI1:  973 , AI2:  5884`
`AI1:  973 , AI2:  5884`
`AI1:  980 , AI2:  5877`
`AI1:  0 , AI2:  5884`      <--
`AI1:  973 , AI2:  5877`
`AI1:  973 , AI2:  5877`
`AI1:  980 , AI2:  5877`
`AI1:  973 , AI2:  5884`
`AI1:  973 , AI2:  5877`
`AI1:  980 , AI2:  5884`
`AI1:  980 , AI2:  5877`
`AI1:  973 , AI2:  5877`
`AI1:  980 , AI2:  5884`
`AI1:  973 , AI2:  5877`
`AI1:  973 , AI2:  5877`
`AI1:  973 , AI2:  5877`
`AI1:  980 , AI2:  5877`
`AI1:  973 , AI2:  5877`
`AI1:  980 , AI2:  5877`
`AI1:  973 , AI2:  973`  <--
`AI1:  0 , AI2:  5869`    <--
`AI1:  980 , AI2:  973`  <--
`AI1:  980 , AI2:  5877`
`AI1:  973 , AI2:  5877`
`AI1:  973 , AI2:  5884`
`AI1:  973 , AI2:  5877`
`AI1:  973 , AI2:  5884`
`AI1:  973 , AI2:  5877`
`AI1:  980 , AI2:  5877`
`AI1:  973 , AI2:  5877`
`AI1:  980 , AI2:  5884`
`AI1:  980 , AI2:  5877`
`AI1:  5884 , AI2:  973` <--
`AI1:  980 , AI2:  5877`
`AI1:  973 , AI2:  5877`
`AI1:  980 , AI2:  5877`
`AI1:  973 , AI2:  5877`
`AI1:  980 , AI2:  5884`
`AI1:  973 , AI2:  5884`
`AI1:  980 , AI2:  5884`
`AI1:  980 , AI2:  5884`
`AI1:  973 , AI2:  5877`
`AI1:  973 , AI2:  5877`
`AI1:  980 , AI2:  5884`
`AI1:  980 , AI2:  5877`
`AI1:  973 , AI2:  5877`
`AI1:  980 , AI2:  5877`
`AI1:  973 , AI2:  5884`
`AI1:  980 , AI2:  5884`
`AI1:  973 , AI2:  5877`
`AI1:  973 , AI2:  5877`
`AI1:  980 , AI2:  5877`
`AI1:  973 , AI2:  5877`
`AI1:  973 , AI2:  0`     <--
`AI1:  973 , AI2:  5877`

This is all pretty random, sometimes the value read is zero and sometimes the value read is the same as the other input.
I also see a difference in the value to raise, about 2 to 3% less. (I tested with several power supplies and several peripherals, the result is the same).

A doubt then comes to me about the kernel. To test this, I made a python script to directly access the SPI port of the card and record the values ​​(I had to remove the "`dtoverlay = ionipi`" for this to work). The problem is no longer. So I think there must be a problem with the ionipi kernel. This proves that the card is working fine;).

What did you thinks? Is it possible to correct this?

I use the digital inputs, the open collector outputs and the relays thanks to the kernel and it works very well.

**Comment by giampiero7** [comment]
Hi @Dalidos ,
Thanks for the report!
Could you share the Python script that gives the reported output?
If you prefer, send it to giampiero@sferalabs.cc
Thanks!

**Comment by Dalidos** [comment]
This problem is solved for me. I think it's a problem of organizing parallel reading or writing.
Everything is working now.
Thank you for giving me your time.

**Comment by giampiero7** [comment]
Yes, commits e9520ac47a92822a37694447a494d893a6d60217 and 73fb2df0428a407e3c52b9b7f3807f7e748f9534 fixed an issue on concurrent readings on analog inputs.
Thank you for your report!
