### ISSUE TITLE
Raspberry Pi 5 support

### ISSUE THREAD

**Issue by alex85us** [sfera-labs/iono-pi-kernel-module#6]
While installing drivers on Raspbian Debian 12 Bookworm on a Raspberry PI 5 does not create the /sys/class/ files.
Linux 6.1.0-rpi7-rpi-2712 on aarch64

$ echo F > /sys/class/ionopi/relay/o1
-bash: /sys/class/ionopi/relay/o1: No such file or directory

Does not provide any error while installing the drivers

**Comment by giampiero7** [comment]
Hi @alex85us ,
Sorry for the belated response.
I cannot recreate your issue, all seems to work properly.
What do you see if you run the command below?
```
dmesg | grep iono
```
Thanks!

**Comment by alex85us** [comment]
[ 6870.371055] ionopi spi0.0: supply vref not found, using dummy regulator
[ 6870.371095] ionopi: - | mcp3204 probed
[ 6870.371134] ionopi: * | error setting up GPIO 16
[ 6870.376259] ionopi: * | init failed
[ 6870.379843] ionopi: - | mcp3204 removed
[ 6870.432591] ionopi: - | init
[ 6870.751059] ionopi spi0.0: supply vref not found, using dummy regulator
[ 6870.751099] ionopi: - | mcp3204 probed
[ 6870.751135] ionopi: * | error setting up GPIO 16
[ 6870.756350] ionopi: * | init failed
[ 6870.759893] ionopi: - | mcp3204 removed
[ 6870.826447] ionopi: - | init

Got this error multiple times along the screen, basically preparing the same information

**Comment by giampiero7** [comment]
Hi,
Are you using the same SD on the Pi4 and Pi5?
Is it possible GPIO16 is used by something else on the Pi5?
Have you tried it with a newly flashed RPi OS image?

**Comment by alex85us** [comment]
I'm using a new 128G SD Card on a newly flashed RPi OS Image from scratch. Don't think GPIO16 is been used since I just tried to install the drivers but seem that were not installed properly

**Comment by giampiero7** [comment]
Hi Alex,
After a full upgrade to the latest OS version I managed to reproduce your issue.
Apparently this is due to changes in the latest kernel on the GPIO numbering on the Pi 5.
We'll release support for the Pi 5 as soon as possible.

**Comment by alex85us** [comment]
Hi Giampiero,
I'm glad you were able to reproduce the issue. Thanks for your quick response one more time.
Regards,
Alex
